services:
  finance-tracker-database:
    container_name: finance-tracker-database
    image: mongo:8.2
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d:ro
      - mongo_data:/data/db

volumes:
  mongo_data:
