quarkus.http.port=${HTTP_PORT:8080}
quarkus.mongodb.connection-string=${MONGODB_URL:mongodb://root:password@localhost:27017/finance_tracker?authSource=admin}
quarkus.mongodb.database=${MONGODB_DATABASE:finance_tracker}
